### ISSUE TITLE
Incompatibility of "gentrans.py" Scripts and Current lit_gpt Library

### ISSUE THREAD

**Issue by N-Orien** [YUCHEN005/GenTranslate#4]
Hi,
very interested in your work. 
However, It seems that there is a problem with "gentrans.py" scripts not being compatible with the provided lit_gpt library. 
(e.g. "lit_gpt/gentrans.py" is calling the "RoPECache" class from "lit_gpt/model.py," which doesn't seem to exist.)
I suspect that "gentrans.py" might be intended to work with an older version of lit_gpt, but the version provided here appears to have been updated.

Could you please fix this issue or let me know which version of lit_gpt you used?
Apologies if I missed anything.

**Comment by YUCHEN005** [comment]
Hi, thanks a lot for reporting it. Yes, it is because my code is built based on old lit-gpt, which is incompatible with new versions.

I have upload those old lit-gpt code, which should match the running scripts. please try it and report any new issues if exist, thanks!

**Comment by N-Orien** [comment]
Thank you for the reply.

The "gentrans.py" scripts seem to be compatible with the lit_gpt library now. 
However, a new issue has arisen: 
When using "infer.sh" to load your checkpoints, 
there is an error indicating a large number of missing keys in the state_dict.

Could you please have another check?
Thanks a lot ^^

**Comment by YUCHEN005** [comment]
Hi, sorry for inconvenience. pls try again it should work now

**Comment by N-Orien** [comment]
Thank you very much 🙏
